Add vaadin-radio-group to the focus-trap tests
vaadin/vaadin-overlay pull request #114
Opened 2018-08-14 08:06 UTC by YuriyVaadin

Connected to https://github.com/vaadin/vaadin-radio-button/issues/77

(Tests without `radio-button` fix should fail on FF only)

Requires https://github.com/vaadin/vaadin-radio-button/pull/79

2018-08-15 10:15 UTC, manolo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  though let's wait until fix for radio-group is released and published to have the build green

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/114#-:-LJx42xp3jawQW76gXgX:b71x9ea)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-20 12:35 UTC, web-padawan requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/114)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-overlay/114#-LKMKHDO5fbroCnGjL8a:-LKMKHDO5fbroCnGjL8b:bz4q5te) (no related file):*
@YuriyVaadin please rebase and you can now rollback change the bower.json 

---


<!-- Sent from Reviewable.io -->

2018-08-23 07:31 UTC, web-padawan approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/114)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-23 11:13 UTC, manolo requested changes
There are two failing tests

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/114#-:-LKaUHQn5JvwPSTAL6aY:baq6uzo)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-23 11:13 UTC, manolo approved these changes
<img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/114#-:-LKaUM3Z2CS-VYzhyjxJ:b8b79qu)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-24 06:44 UTC, web-padawan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/114#-:-LKefQZUA0WFndRwrsFx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-24 07:03 UTC, merged